### ISSUE TITLE
terrain rendering glitch

### ISSUE THREAD

**Issue by vs-slavchev** [vs-slavchev/Virtual-Evil#2]
It appears for a split second while moving the character. A row of pixels of the next tile on the tileset is rendered.

![screenshot from 2015-12-02 00-21-26](https://cloud.githubusercontent.com/assets/10689151/12656105/b7c97be0-c5fc-11e5-9f52-a7f9b6e6be31.png)

**Comment by vedi0boy** [comment]
I'm here to help! I had this issue before. It is known as Texture/spritesheet/tiledmap bleeding. There is a simple method to solve this on the LibGDX forums. Here it is: [http://pastebin.com/WXsWxeze](http://pastebin.com/WXsWxeze)
Just pass the texture regions through this method when you load them up.

To be safe add a comment with credit to awilki01. He made that method originally. Here: http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=16368
P.S. I replied to your e-mail :)

**Comment by vs-slavchev** [comment]
fixed it! thank you very much for the help!
